# Generated by Django 5.0 on 2023-12-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0004_remove_order_cart_remove_cart_item_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=250),
        ),
    ]
